### PR TITLE
add/update results section

### PR DESCRIPTION
**Pull request by tomkralidis**
As discussed.  Below is a screenshot of the rendered output for context:

image

### CODE REVIEW

**Comment by tomkralidis** [comment]
FYI @antje-s we need `de-dwd-global-discovery-catalogue` to be added to the Global Registry.

**Review by jmaxmarno — APPROVED** [review]

**Review by antje-s — APPROVED** [review]

**Comment by antje-s** [comment]
oh I just realised that Saudi Arabia is missing in the tables

**Comment by tomkralidis** [comment]
I don't see Saudi Arabia anywhere in https://codes.wmo.int/wis/topic-hierarchy/_centre-id ?  Do they need to be registered? cc @amilan17

**Comment by antje-s** [comment]
> FYI @antje-s we need `de-dwd-global-discovery-catalogue` to be added to the Global Registry.

Shouldn't this be done ‘automatically’ via the official registration process?

**Comment by tomkralidis** [comment]
> > FYI @antje-s we need `de-dwd-global-discovery-catalogue` to be added to the Global Registry.
> 
> Shouldn't this be done ‘automatically’ via the official registration process?

Correct.  Not sure of its status in the WMO Global Registry @chenxiaoxia2019 @amilan17

**Comment by chenxiaoxia2019** [comment]
> > > FYI @antje-s we need `de-dwd-global-discovery-catalogue` to be added to the Global Registry.
> > 
> > 
> > Shouldn't this be done ‘automatically’ via the official registration process?
> 
> Correct. Not sure of its status in the WMO Global Registry @chenxiaoxia2019 @amilan17

Hi, Tom. The GDC (DWD) was added to the Global Registry. Additionally, GDC (KMA) was removed as they decided not to provide such service.

**Comment by tomkralidis** [comment]
FYI this PR has been updated with updated structure for GB testing and a sample report for `fr-meteofrance-global-broker`.

A [PDF](https://github.com/user-attachments/files/16909074/wis2-global-services-testing-DRAFT.pdf) is included for reviewing in context.

Based on the initial "reports" GB, GC, GDC, the expectation will be for additional reports to created from the templates (per global service).

**Pull request merged**
