### PR TITLE
GDC: update setup/teardown

### PR DESCRIPTION
**Pull request by tomkralidis**

### CODE REVIEW

**Comment by antje-s** [comment]
Perhaps adding under 
==== Entering the test environment
- backup metadata repository
- backup metrics 

- Exemplary description of 
- - how to empty metadata repository or switch to an empty test repository

==== Exiting the test environment
- Exemplary description of 
- - how to restore repository / metrics

change proposal
- restoration of resources at state prior to entry:
   - metadata archive zipfile (create new archive file or restore the backed-up file)

**Comment by tomkralidis** [comment]
Thanks @antje-s.  I think the "how to" steps are implementation specific (a given GDC has its own "way" to clean its metadata repository i.e. delete all records, switch to another underlying DB/NoSQL store, etc.).  Or are you thinking something else?

I've updated the exit details with your metadata archive proposed addition -- thanks.

**Review by antje-s — CHANGES_REQUESTED** [review]
added
section preparations

deleted
- empty metrics endpoint
--> since the test uses the difference before/after the test case, uninitialised metrics should also be unproblematic

**Comment by tomkralidis** [comment]
Thanks @antje-s, makes sense.

**Review by antje-s — APPROVED** [review]

**Pull request merged**
